### ISSUE TITLE
attempting install 

### ISSUE THREAD

**Issue by interfaith** [dwyl/image-uploads#7]
W20150221-18:55:05.788(-8)? (STDERR) ReferenceError: require is not defined
W20150221-18:55:05.788(-8)? (STDERR)     at app/node_modules/imagemagick/imagemagick.js:1:52
W20150221-18:55:05.789(-8)? (STDERR)     at app/node_modules/imagemagick/imagemagick.js:417:3

**Comment by nelsonic** [comment]
@interfaith we wrote this 10 months ago. Sadly, Meteor has made ***Breaking Changes*** since then. 
the error messages you have pasted are quite easy to get passed with a bit of googling.
We have not updated this code because we are no longer using Meteor.
Please feel free to fork and send PullRequest when you get it working.
Recommend using https://github.com/aheckmann/gm instead of imagemagick.

**Comment by nelsonic** [comment]
If this is still an issue, please raise it here: https://github.com/ideaq/image-uploads 
Thanks!
